server:
  port: 8080

spring:
  application.name: backend-resources
  security:
    saml2:
      relyingparty:
        registration:
          endpoint:
            signing:
              credentials:
                - private-key-location: classpath:ilta-test.key
                  certificate-location: classpath:ilta-test.crt
            singlelogout:
              binding: POST
              response-url: "{baseUrl}/logout/saml2/slo"
#            assertionConsumerServiceLocation: """
            assertingparty:
              metadata-uri: "classpath:idp-metadata.xml"
            acs:
              location: "http://backend-keycloak-auth:8080/realms/My_realm/broker/suomifi-ilta-saml/{registrationId}"
            entity-id: "https://ilta.112.fi/auth/dev/keycloak/redirect2"

